version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: mysql
      DB_DATABASE: example
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: redis
      REDIS_HOST: redis
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: webserver.dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-confs/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  redis:
    image: redis
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  dbdata:
    driver: local